name: ViaVersion
main: us.myles.ViaVersion.ViaVersionPlugin
authors: [_MylesC, creeper123123321, Gerrygames, KennyTV, Matsv]
version: ${project.version}
description: ${project.description}
load: postworld
api-version: 1.13
loadbefore: [ProtocolLib, ProxyPipe, SpigotLib, SkinRestorer]
softdepend: [ProtocolSupport, PacketListenerApi]